# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
x = torch.rand(7,7)
x
# Create random tensor


tensor([[0.8393, 0.6438, 0.6650, 0.8913, 0.7645, 0.1855, 0.2245],
        [0.7474, 0.9038, 0.7704, 0.8220, 0.1423, 0.2348, 0.9368],
        [0.4159, 0.6902, 0.1661, 0.7408, 0.4589, 0.9130, 0.8630],
        [0.3128, 0.0106, 0.9836, 0.3063, 0.0825, 0.0913, 0.7683],
        [0.7072, 0.7940, 0.1717, 0.6521, 0.2848, 0.1878, 0.4912],
        [0.1376, 0.9088, 0.1891, 0.2787, 0.3045, 0.6634, 0.8235],
        [0.6141, 0.7552, 0.7925, 0.8527, 0.2929, 0.7573, 0.0348]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
x2 = torch.rand(1,7)
torch.mm(x, x2.T)

# Perform matrix multiplication


tensor([[2.1179],
        [2.0936],
        [1.7369],
        [1.2176],
        [1.4521],
        [1.2549],
        [2.2254]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x1 = torch.rand(7,7)
x2 = torch.rand(1,7)
x3 = torch.rand(1,7)

# Matrix multiply tensors
x4 = torch.mm(x1, x2.T)
x5 = torch.mm(x4, x3)
print(x5)


tensor([[1.0999, 0.2083, 0.2845, 0.4482, 1.3466, 1.3000, 0.3779],
        [1.1632, 0.2203, 0.3009, 0.4740, 1.4242, 1.3749, 0.3997],
        [1.3574, 0.2571, 0.3512, 0.5531, 1.6619, 1.6043, 0.4664],
        [1.8081, 0.3425, 0.4678, 0.7368, 2.2137, 2.1370, 0.6213],
        [1.0124, 0.1917, 0.2619, 0.4125, 1.2395, 1.1966, 0.3479],
        [1.5001, 0.2841, 0.3881, 0.6113, 1.8367, 1.7730, 0.5155],
        [1.0671, 0.2021, 0.2761, 0.4348, 1.3064, 1.2612, 0.3667]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [23]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
X = torch.rand(2,3).to(device)
Y = torch.rand(2,3).to(device)
print(X)
print(Y)


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [24]:
# Perform matmul on tensor_A and tensor_B
Z = torch.mm(X, Y.T)
print(Z, Z.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [25]:
# Find max
print(Z.max())

# Find min
print(Z.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [26]:
# Find arg max
print(Z.argmax())

# Find arg min
print(Z.argmin())


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
X = torch.rand(1,1,1,10)

# Remove single dimensions
X_squeezed = X.squeeze()

# Print out tensors and their shapes
print(X, X.shape)
print(X_squeezed, X_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
